baseurl = "https://zhiweiyin318.github.io"
title = "Zhiwei Yin"
theme = "beautifulhugo"
metaDataFormat = "yaml"
DefaultContentLanguage = "en"
hasCJKLanguage = true
useHLJS = true
#pygmentsStyle = "monokai"
#pygmentsUseClassic = true
#pygmentsUseClasses = true
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
disqusShortname = "zhiweiyin"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Lazy Coder"
  logo = "images/avatar-icon.png"
  favicon = "images/favicon.ico"
  dateFormat = "Mon Jan 2, 2006"
  commit = false
  rss = true
  baiduKey = "" # Baidu analytics
  comments = true
 
  #gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
 
 # readingTime = true
  wordCount = true
  #socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  
[[Params.bigimg]]
 src = "images/backend-pic.jpg"
 #desc = "code"
# [[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
# [[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Zhiwei Yin"
  website = "https://zhiweiyin318.github.io"
  email = "zhiweiyin@hotmail.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "zhiweiyin318"
  weibo = "yzw517318"
  #gitlab = "username"
  #twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
 # paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "categories"
    name = "categories"
    weight = 2

[[menu.main]]
    parent = "categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 2

[[menu.main]]
    parent = "categories"
    name = "golang"
    url = "categories/golang"
    weight = 3

  [[menu.main]]
    parent = "categories"
    name = "python"
    url = "categories/python"
    weight = 4

 [[menu.main]]
    parent = "categories"
    name = "quant"
    url = "categories/quant"
    weight = 5

 [[menu.main]]
    parent = "categories"
    name = "translation"
    url = "categories/translation"
    weight = 6

  [[menu.main]]
    parent = "categories"
    name = "tags"
    url = "tags"
    weight = 7

[[menu.main]]
    identifier = "archives"
    name = "archives"
     url = "/post"
    weight = 3

[[menu.main]]
    identifier = "notes"
    name = "notes"
    weight = 4

[[menu.main]]
    parent = "notes"
    name = "kubernetes demo"
    url = "k8s-demo"
    weight = 1


[[menu.main]]
    identifier = "projects"
    name = "porjects"
    weight = 5

[[menu.main]]
    parent = "projects"
    name = "Kquant"
    url = "https://github.com/zhiweiyin318/kquant"
    weight = 1

[[menu.main]]
    name = "about"
    url = "/about"
    weight = 6


